name: LeechBot Environment

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values if you have forked it for your own works
  GitHubMail: "prajwal.suresh27@gmail.com"
  GitHubName: "PrajjuS" 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clone The Secret Leech Repository
        run: |
          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/PrajjuS/PrajwalLeecherBot.git source

      - name: Compiling The Leech Docker Container
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t torbot
          docker image ls

      - name: running Docker
        timeout-minutes: 340
        continue-on-error: true
        run: |
          docker run --privileged --rm -i torbot

      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN2 }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GH_TOKEN2 }}@github.com/${GITHUB_REPOSITORY} HEAD:main
